### PR TITLE
Improve diff header

### PR DESCRIPTION
**Pull request by pradyunsg**
Before:

screen shot 2017-11-25 at 12 48 44 pm

After:

screen shot 2017-11-25 at 12 48 53 pm

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @pradyunsg!

I'd prefer not to increase the height of the `diffbar`, instead please adjust the padding:

```css
.diffbar {
  padding-top: 10px !important;
}
```

I didn't notice the problem before because I have [GitHub-Dark](https://github.com/StylishThemes/GitHub-Dark) installed and it positions the content correctly.

**Comment by pradyunsg** [comment]
Hello There!

Squash merge please. ;P

**Comment by Mottie** [comment]
Thanks!!

**Comment by pradyunsg** [comment]
You're welcome! ^>^

Not to be pushy, when do you plan to tag the next release? :)

**Comment by Mottie** [comment]
Once I get #10 fixed, and finish the work I started on creating a user.css version... later today, maybe?

**Comment by Mottie** [comment]
Next release now available.

Also, if you're using the latest version of Stylus, you can install the user.css version directly from the GitHub repository... see the main [readme](https://github.com/StylishThemes/GitHub-FixedHeader#readme).

**Comment by pradyunsg** [comment]
Okay... Umm... this release broke the default view for me...

screen shot 2017-12-02 at 2 19 16 am

@Mottie Would you be open to the idea of reverting this specific and make the styling size consistent with Github right now (as proposed initially?)

screen shot 2017-12-02 at 2 19 31 am

**Comment by Mottie** [comment]
> this release broke the default view for me.

I wouldn't say that a (significant) gap is "breaking" the view... I don't think it's pretty but it's needed to fix the problems added when the Refined GitHub extension is active - see issue #10.

If you really hate the gap, try out my [GitHub Diff Files Filter](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-diff-files-filter) userscript to fill that gap. I was using the userscript which is why I couldn't reproduce the problem in issue #10 for so long. Otherwise, I'd love some help with an alternative fix.

And I still don't like the idea of increasing the second sticky header by 20px because it's eating up viewport real estate that I think is better served showing the diff code instead of blank space... that and Refined GitHub adds a tertiary sticky header (file name).

**Pull request merged**
