### PR TITLE
Fix logo overlap on session authentication

### PR DESCRIPTION
**Pull request by stonecrusher**
2019-02-28-confirm password

### CODE REVIEW

**Comment by the-j0k3r** [comment]
Thanks =)

**Comment by stonecrusher** [comment]
Oh.. uhm... version number in package.json should be 1.2.8, not 1.2.7

**Comment by the-j0k3r** [comment]
According to the history https://github.com/StylishThemes/GitHub-FixedHeader/commits/master/package.json  seems right. The only thing missing is the tags which are usually done by persons making release after bumping the versions.

But I see that the version in usercss is actually the one wrong, I should have opened my eyes on the review I guess.

For future reference versioning is handled by `npm run-script patch` see other commands here https://github.com/StylishThemes/GitHub-FixedHeader/blob/40df0a6bc16198192a75040fa38d352c9d711110/package.json#L23-L25 and not manually.

However its best to leave releases to us because well also push tagging etc.

**Comment by the-j0k3r** [comment]
All fixed now, thanks.

**Pull request merged**
